### ISSUE TITLE
Alarm Control Panel Not Found During Alexa Component Discovery

### ISSUE THREAD

**Issue by jpreiditsch** [uvjustin/alarmdotcom#30]
From https://www.home-assistant.io/integrations/alexa.smart_home/

Alexa does not support arming with voice PIN at this time. Therefore if the Alarm Control Panel requires a code for arming or the code_arm_required attribute is true, the entity will not be exposed during discovery. The Alarm Control Panel may default the code_arm_required attribute to true even if the platform does not support or require it. Use the Entity Customization Tool to override code_arm_required to false and expose the Alarm Control Panel during discovery.

I was unable to get this to successfully work with the customizations.yaml even if it shows code_arm_required: false in the developer tools. I'm not using Alexa through Nabu Casa.

Likely a race condition where the customization is not applied until after the alexa component is loaded.

I found that adding an override to the implement of AlarmControl panel to set the value to false works.

```
    @property
    def code_arm_required(self):
        """Whether the code is required for arm actions."""
        return False    
```

This should probably be implemented in a nicer manner in a configurable manner.

**Comment by uvjustin** [comment]
It's an easy change to also change the code_alarm_required property to return False when there is no code, but I checked and that property is not overridden in most of the alarm integrations, including invisalink, ialarm, ifttt, and simplisafe. Instead, a code_format of None is returned when there is no code, and this seems like the suggested way to do it based on the code comments in the alarm_control_panel base class as well as here: https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/.
I'm not familiar with the Alexa integration but given the above it would make more sense for that integration to check the code_format field for None instead of checking the code_arm_required field.
If you can work around this locally for now then I would go ahead and do that. If there is a change to the HA core to start using the code_alarm_required property then I will make those changes here as well.
