### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cjeffcoat80** [uvjustin/alarmdotcom#35]
I am getting a error message in the log section of home assistant. I am curious as to if this is normal. The message says Can not load state data from Alarm.com. it has shown up 6 times. I am kinda new and do not know much about coding or programing. 

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:233
First occurred: 3:15:13 AM (6 occurrences)
Last logged: 3:31:13 AM

Can not load state data from Alarm.com

Also I have noticed that when I restart Home Assistant I get a warning that states this:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:476
First occurred: 3:15:09 AM (6 occurrences)
Last logged: 3:31:09 AM

Update of alarm_control_panel.alarm_com is taking over 10 seconds

Everything is functioning fine though. I do not have any issues with the alarm arming and disarming in automations or manually from Home Assistnat.

If these are normal then I can ignore them and be ok with that. Just want to be sure.

thank you guys for all your help

**Comment by xtacle101** [comment]
I'm seeing the same. Seems to be functioning fine, but getting multiple warnings and errors:

ERROR:
```
Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:178
First occurred: March 8, 2021, 9:09:01 PM (124 occurrences)
Last logged: 11:20:20 AM

Can not load state data from Alarm.com
```

WARNING:
```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:605
Integration: Alarm control panel (documentation, issues)
First occurred: March 8, 2021, 9:22:46 PM (72 occurrences)
Last logged: 11:20:20 AM

Updating alarmdotcomajax alarm_control_panel took longer than the scheduled update interval 0:00:30
```

WARNING:
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:476
First occurred: March 8, 2021, 9:08:56 PM (158 occurrences)
Last logged: 11:19:30 AM

Update of alarm_control_panel.panel is taking over 10 seconds
```

**Comment by mikesalz** [comment]
I am getting a ton of these lately as well.

> Logger: pyalarmdotcomajax.pyalarmdotcomajax
> Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:233
> First occurred: 6:00:01 PM (22 occurrences)
> Last logged: 8:12:31 PM
> 
> Can not load state data from Alarm.com

**Comment by uvjustin** [comment]
It's normal to get these every once in a while - it happens when there is a timeout when trying to load the partitions endpoint. If it's happening a ton then that's concerning, but I don't seem to have that problem on my end. Since the code hasn't changed in a while and the integration still works, I would look into other things which might be causing sporadic connection issues.

**Comment by xtacle101** [comment]
I've seen the "Can not load state data from Alarm.com" 137 times in the last 12 hours. Not sure the frequency at which it's trying to know if that's a good or bad "success rate". I was seeing issues with my internet connection throughout the day today, but have since resolved them. It still seems to be throwing the errors at the same rate. I'll keep an eye on it.

**Comment by uvjustin** [comment]
The default scan interval for HA alarm panels is 30 seconds, so 137 is quite high - it's as if your internet was out for over an hour...

**Comment by uvjustin** [comment]
Yes, remove the old component.
The other posts have logs which reference `pyalarmdotcomajax` which is still the correct pypi library, but I don't see any posts referencing `alarmdotcomajax` besides yours.

**Comment by mikesalz** [comment]
Yeah, I have had 142 occurrences just since I restarted HA last night around 6 pm.  As others have said, the integration does appear to be working.  I am using ADT, which has had some ugly issues in the past.  @cjeffcoat80 @xtacle101 Are you also using ADT?  Maybe it is on their end...

**Comment by cjeffcoat80** [comment]
I am not. My alarm company is Vector Security. I just deleted everything and started over. Everything seems to be working correctly now. However do not forget to go into the custom components file and in the manifest.json file add line 10 which is the version line.

**Comment by cjeffcoat80** [comment]
I think with ADT you have to enable the 2 factor authentication

**Comment by cjeffcoat80** [comment]
never mind my errors are back.

**Comment by uvjustin** [comment]
@mikesalz Yes that looks problematic. Unfortunately I don't have much time to investigate at the moment...

One thing you guys could try is just logging on to the website and hitting refresh every 30 seconds or so to see if you notice anything weird.

**Comment by mikesalz** [comment]
Hey @uvjustin! I logged in and refreshed a few times, and everything seemed fine.  But I don't think that really tells us much.

You can see from a sample of my log that the problem is very intermittent, but happens very often.  I get that you're busy, and I hate to bug you.  Any suggestions on something I can do myself on my end to try to resolve it?


>
> 2021-03-11 17:08:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:11:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:12:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:12:41 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:14:41 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:15:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:28:41 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:41:12 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:41:42 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 17:49:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:09:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:17:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:18:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:29:41 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:33:11 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:41:12 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:48:41 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:49:42 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:50:12 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 18:55:42 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com
> 2021-03-11 19:00:12 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com

**Comment by uvjustin** [comment]
It seems to happen sporadically and usually not twice in a row. Maybe check your DNS servers?
You could also try increasing the `scan_interval` to 60 to see if there's some kind of rate limiting from the server going on.

**Comment by mikesalz** [comment]
I can give scan_interval a try.  I didn't see it in the documentation.  Would it be something like this?

```
alarm_control_panel:
  - platform: alarmdotcom
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    scan_interval: 60
```

**Comment by uvjustin** [comment]
Yes that's how you would use it.
https://www.home-assistant.io/docs/configuration/platform_options/
I didn't document it here because it's really inherited from HA, and I think most users should just stick to the default of 30.

**Comment by mikesalz** [comment]
Well, I tried `scan_interval` this morning but it didn't make a difference. :(

**Comment by xtacle101** [comment]
> Are you also using ADT? Maybe it is on their end...

I do not use ADT

> Yes, remove the old component.

I removed the old component, which at least helped in removing the multiple attempts, but i do still see a lot of failed attempts using just the current component. I'll try increasing the scan_interval to 60 as well to see if that improves things.

appreciate all your work @uvjustin keeping this integration alive!

**Comment by xtacle101** [comment]
still lots of errors and warnings:

```
Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:236
First occurred: March 14, 2021, 3:45:54 PM (4 occurrences)
Last logged: 8:23:57 AM

Unable to extract state data from Alarm.com
```

```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:605
Integration: Alarm control panel (documentation, issues)
First occurred: March 14, 2021, 3:05:54 PM (21 occurrences)
Last logged: 8:32:56 AM

Updating alarmdotcom alarm_control_panel took longer than the scheduled update interval 0:01:00
```

```
Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.8/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:233
First occurred: March 14, 2021, 2:55:10 PM (87 occurrences)
Last logged: 8:40:11 AM

Can not load state data from Alarm.com
```

**Comment by mikesalz** [comment]
I was hoping this was a temporary issue, but it has been happening in my HA installation for two weeks.  139 occurrences just since yesterday evening.  @uvjustin if/when you have time to look into this, I can provide a temporary login for you to test with.  I am happy to help in any way.  Just let me know!  Thanks!

**Comment by uvjustin** [comment]
I won't have time to look at this for at least a couple of weeks. Your logs look like it rarely happens back to back, so it really shouldn't affect usability - maybe just ignore the error for now?

**Comment by uvjustin** [comment]
Actually it's not related but I'll still have a quick look to see if I can find anything.

**Comment by mikesalz** [comment]
Hey @uvjustin !  So, get this... Until this Monday, I had a Fios G1100 modem connected to my Orbi mesh system (in AP/bridge mode).  On Monday I had Frontier Fios bump up my internet speed.  As part of the internet upgrade, I decided to ditch the G1100 and went straight to the Orbi.  

Now that the Orbi handles DHCP, the error has all but disappeared!  I have only received it 2-3 times since the change.  Where previously I had received hundreds per day.  I don't know if this is related or coincidental, but it does seem as though removing the old router might have fixed the issue.  I am keeping an eye on it, and will let you know if anything changes.

**Comment by uvjustin** [comment]
Makes sense - seemed like a networking issue

**Comment by xtacle101** [comment]
> I had a Fios G1100 modem connected to my Orbi mesh system (in AP/bridge mode)

very interesting... i've also got a Orbi Mesh system in AP mode for my Wi-Fi. I have a different router\firewall, which acts as my DHCP server, but seems interesting there's a common item there.

> I had the previous router configuration for years.

same, no changes during the time this popped up.

I disconnected my satellite and restarted my security panel to ensure the panel connects to the closest Wi-Fi node. I've received the error once since that point, but I'll keep an eye on it.

@uvjustin please correct me where i'm wrong here, but this integration doesn't communicate with anything on our internal network right? The security system on our local LAN sends it's info/status to the service provider. This app pulls/scrapes that info from their site and pulls it back into home assistant. Seems like the issue is in the integration's communications with the service provider via WAN, and nothing via LAN. I could be totally off base here - I'm only asking to make sure I'm keeping my eyes focused on the right areas to help troubleshoot.

Again - Appreciate everyone's contribution in troubleshooting, and thanks again @uvjustin for your continued efforts!

**Comment by mikesalz** [comment]
@xtacle101 If the issue continues for you, it might be interesting to see what happens if you bypass your other router and use the Orbi for DHCP.  Although, I realize what a pain in the butt that can be.  I had a bunch of devices with static internal IPs, and I had to reconfigure most of them after the changeover.

**Comment by xtacle101** [comment]
@mikesalz my router currently has reservations for every device on my network, so all devices have/had consistent IPs. Haven't had any changes there.

**Comment by uvjustin** [comment]
Yes, it's only communicating on the LAN.
I mentioned earlier that I suspected a DNS issue. See https://www.google.com/search?q=orbi%20dns%20issue

**Comment by uvjustin** [comment]
Yes, it's only communicating on the WAN.
I mentioned earlier that I suspected a DNS issue. See https://www.google.com/search?q=orbi%20dns%20issue

**Comment by uvjustin** [comment]
Still, this most likely has to do with your network and not the component.

**Comment by xtacle101** [comment]
@cjeffcoat80 do you have a pihole or similar DNS blackhole on your network? When I find time, that's where I'm looking next. That and the Orbi issue. Mine Orbi setup is only running as an AP and the device where Home Assistant runs doesn't touch Wi-Fi, but still an interesting coincidence.

**Comment by cjeffcoat80** [comment]
Not that I am aware of. I have 2 APs that I am using. My home assistant does get access to the web. I can't see it being my network bc everything else is fine and the website works flawlessly.

**Comment by westerncanada** [comment]
First off thanks for this component, it's absolutely amazing and I love it.

I'm seeing the same thing as well. 

No Orbi here. I'm using Edgerouters and HP procurve network gear.

I'm running HA on a Pi 4 4GB, on a external SSD in a venv, without DNS blockers. CPU and memory use is light.

Wired Ethernet only.

I've set the Pi to use my local pair of BIND recursive servers.
Nothing on the resolvers show issues with looking up the name.

The weird part is, everything other than the log entry seems to be working fine.

Apr 02 22:49:45 rpi04 hass[1510]: 2021-04-02 22:49:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.alarm_com is taking over 10 seconds
Apr 02 22:49:53 rpi04 hass[1510]: 2021-04-02 22:49:53 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Can not load state data from Alarm.com

I'm a network engineer by trade, so if you would like help debugging this, I'm able to assist because I'm getting the same errors.

I'm not great with python, but is there a way to temporarily log what the component is getting from the website to see if its valid? Unfortunately Wireshark won't easily decrypt https streams.

**Comment by uvjustin** [comment]
@westerncanada How often are you getting this error?
I can change the logger to output more debug info, but that change would be in the in the `pyalarmdotcom` library. You'd have to install a custom version of the `pyalarmdotcom` library. If you're fine with that I can set up a new branch of the `pyalarmdotcom` library and you could try to look at that output.
Can you use a tool like smokeping to monitor the connectivity from your HA instance throughout the day?

**Comment by cjeffcoat80** [comment]
is there any way you can extend the amount of time it takes to update from 10 seconds to maybe 20 or 30 seconds in your code?

**Comment by uvjustin** [comment]
@cjeffcoat80 There isn't a 10 second update limit in the code. The 10 second slow update warning is hard coded into the HA entity helper and will fire when a component is slow to update. From the log messages you post, it looks like HA asks the alarm component to update, then it sends a message after 10 seconds saying the update is slow, and then about 4-5 seconds later (ie 15 seconds after the update began) the alarmdotcom component update fails and the log is printed. The log message comes from an aiohttp.ClientError, which means that the https connection to the ADC endpoint failed. That failure is out of scope of this component.
I really believe this is an intermittent network issue on your end or between your server/ADC, but that can be hard to diagnose. Hopefully @westerncanada can help us dig into this since he/she is a network engineer.
Unfortunately I can't really spend time troubleshooting an issue I can't reproduce on my end.
For more info on the 10 second warning try looking on the HA forums https://community.home-assistant.io/t/hassio-io-10-second-warnings/23714

**Comment by firstdominator** [comment]
Exactly same issue here. Router settings did not changed for the last 2-3 years. No problem before. 
Anyone found a solution for this?

Also when I look into my custom_components folder I have one folder called "alarmdotcom" and one folder called "alarmdotcomwebapi". I'm just concerned about the second one.. should it be there? Or should I delete that folder?

Thanks for all your help.
