### ISSUE TITLE
beautifulsoup errors on HA 2021/10 - HA 2021/12

### ISSUE THREAD

**Issue by rintaran** [uvjustin/alarmdotcom#62]
So I have this alarmdotcom integration fully functional on HA 2021/9, however, more recent versions seem to be causing issues.
I get the following related errors:

Logger: homeassistant.config
Source: config.py:883
First occurred: 9:36:11 AM (1 occurrences)
Last logged: 9:36:11 AM
Platform error: alarm_control_panel - Requirements for alarmdotcom not found: ['beautifulsoup4==4.9.3'].

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 9:35:54 AM (3 occurrences)
Last logged: 9:36:11 AM
Unable to install package beautifulsoup4==4.9.3: ERROR: Will not install to the user site because it will lack sys.path precedence to beautifulsoup4 in /snap/home-assistant-snap/452/lib/python3.9/site-packages WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available. You should consider upgrading via the '/snap/home-assistant-snap/452/bin/python3.9 -m pip install --upgrade pip' command.

Would love any help I can get on this, as it's well beyond my very limited abilities. The alarmdotcom integration is pretty integral to keeping my spouse onboard with HA.

**Comment by uvjustin** [comment]
Thanks for filing the issue. I guess this is probably because you use the HA component scrape, and beautifulsoup4 was bumped to a newer version in this https://github.com/home-assistant/core/pull/56764 .
We'll have to bump the version here to match the version there. I'm going to wait another week since we have some other PRs here to push through at the same time.

**Comment by rintaran** [comment]
The latest update appears to have solved this issue. Thanks @uvjustin !
