### ISSUE TITLE
Alarm Trigger

### ISSUE THREAD

**Issue by kitracer** [uvjustin/alarmdotcom#65]
Is there a way to see when a state of "alarm" is active? I'm only able to see disarmed, armed_home and armed_away.
Thanks!

**Comment by elahd** [comment]
Are you comfortable with using the command line? You could help by sharing a some of the data returned by Alarm.com's servers when your alarm is active. I can follow up with instructions if you're able to help.

With that said, keep in mind that the actual Home Assistant integration works by requesting updates from Alarm.com every couple of _minutes_. I'm not sure that it's valuable or otherwise a good idea to rely on this integration for anything safety related. Viewing disarmed/armed statuses and whether a window is open is one thing. Relying on this for a critical alert like an alarm activation is way sketchier.

**Comment by kitracer** [comment]
I think I'll heed your warning about the delay.
My planned workaround is to have the alarm.com system trigger a MIMOlite
when the system is in duress. The MIMOlite then turns on our siren and also
triggers a Shelly 2.5 connected to Home Assistant. I should then be able to
run an automation based off of the status of the Shelly 2.5.
What do you think?
Thanks again for the help!

**Comment by uvjustin** [comment]
The component uses polling, and the default polling interval for alarm panels in Home Assistant is 30 seconds. I agree with what was mentioned above - this add on should be used for convenience only.
As for what you mentioned above, I would leave the siren connected directly to your home assistant and connect the MIMOlite in parallel with the siren. The MIMOlite should be able to talk directly to your z-wave stick/HA and you shouldn't need to go through Shelly.

**Comment by kitracer** [comment]
Okay, sounds good. Thanks again!

**Comment by uvjustin** [comment]
Sorry I mistyped that! I meant that your siren should be connected directly to your alarm system.

**Comment by kitracer** [comment]
I knew what you meant :)
We're in a 20,000ft warehouse and the panel siren wasn't loud enough. We
decided instead of running a wire from the panel (for now) to an external
siren to just use the MIMOlite triggered by alarm.com. The MIMO turns on a
very loud siren, an air raid siren and a bunch of cop LED light bars. We've
had 3 break ins in a year so we're trying everything.
